FROM node:22-bookworm-slim AS frontend-dev

WORKDIR /app/frontend

COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

FROM rust:1-bookworm AS backend-dev

WORKDIR /app

RUN cargo install cargo-watch

CMD ["cargo", "watch", "-w", "src", "-w", "../naim-client/src", "-x", "run"]